workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH

image: python:3.12

stages:
  - build
  - lint

before_script:
  - pip install pipx
  - pipx install poetry
  - poetry install --no-root

black:
  stage: lint
  script:
    - poetry run black --diff --check .

isort:
  stage: lint
  script:
    - poetry run isort --check-only .

flake8:
  stage: lint
  script:
    - poetry run flake8 .