workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH

image: python:3.12

stages:
  - build
  - test

before_script:
  - pip install pipx
  - pipx install poetry
  - poetry install --no-root

pytest:
  stage: test
  script:
    - poetry run pytest tests

black:
  stage: test
  script:
    - poetry run black --diff --check src/

isort:
  stage: test
  script:
    - poetry run isort --check-only src/

flake8:
  stage: test
  script:
    - poetry run flake8 src/
