services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - twitter-clone

  app:
    build: .
    container_name: fastapi-app
    depends_on:
      - db
    volumes:
      - ./medias:/app/medias
    ports:
      - "8000:8000"
    networks:
      - twitter-clone

  nginx:
    image: nginx:latest
    container_name: nginx-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
      - ./medias:/app/medias
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - twitter-clone

volumes:
  pgdata:

networks:
  twitter-clone:
    driver: bridge

