services:
  db:
    image: postgres:13
    container_name: postgres-test-db
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
