services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: fastapi-app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/microservice
    ports:
      - "8000:8000"


volumes:
  pgdata:

