services:
  db:
    image: postgres:13
    container_name: postgres-test-db
    environment:
      POSTGRES_DB: microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - twitter-clone-test

  app:
    build: .
    container_name: fastapi-test-app
    depends_on:
      - db
    volumes:
      - ./medias:/app/medias
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - twitter-clone-test

  nginx:
    image: nginx:latest
    container_name: nginx-test-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
      - ./medias:/app/medias
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - twitter-clone-test

#volumes:
#  pgdata-test:

networks:
  twitter-clone-test:
    driver: bridge

